<?php namespace Modules\Admin\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountriesTableSeeder extends Seeder {

	public function run()
	{
		// Africa = 1 | Asia = 2 | North America = 3 | South America = 4  | Europe = 5 | Oceania = 6 | Antarctica = 7

		\DB::table('country')->delete();
		$countries = [
			[ 'code' => 'ABW', 'continent' => 3, 'code2' => 'AW', ],
			[ 'code' => 'AFG', 'continent' => 2, 'code2' => 'AF', ],
			[ 'code' => 'AGO', 'continent' => 1, 'code2' => 'AO', ],
			[ 'code' => 'AIA', 'continent' => 3, 'code2' => 'AI', ],
			[ 'code' => 'ALB', 'continent' => 5, 'code2' => 'AL', ],
			[ 'code' => 'AND', 'continent' => 5, 'code2' => 'AD', ],
			[ 'code' => 'ANT', 'continent' => 3, 'code2' => 'AN', ],
			[ 'code' => 'ARE', 'continent' => 2, 'code2' => 'AE', ],
			[ 'code' => 'ARG', 'continent' => 4, 'code2' => 'AR', ],
			[ 'code' => 'ARM', 'continent' => 2, 'code2' => 'AM', ],
			[ 'code' => 'ASM', 'continent' => 6, 'code2' => 'AS', ],
			[ 'code' => 'ATA', 'continent' => 7, 'code2' => 'AQ', ],
			[ 'code' => 'ATF', 'continent' => 7, 'code2' => 'TF', ],
			[ 'code' => 'ATG', 'continent' => 3, 'code2' => 'AG', ],
			[ 'code' => 'AUS', 'continent' => 6, 'code2' => 'AU', ],
			[ 'code' => 'AUT', 'continent' => 5, 'code2' => 'AT', ],
			[ 'code' => 'AZE', 'continent' => 2, 'code2' => 'AZ', ],
			[ 'code' => 'BDI', 'continent' => 1, 'code2' => 'BI', ],
			[ 'code' => 'BEL', 'continent' => 5, 'code2' => 'BE', ],
			[ 'code' => 'BEN', 'continent' => 1, 'code2' => 'BJ', ],
			[ 'code' => 'BFA', 'continent' => 1, 'code2' => 'BF', ],
			[ 'code' => 'BGD', 'continent' => 2, 'code2' => 'BD', ],
			[ 'code' => 'BGR', 'continent' => 5, 'code2' => 'BG', ],
			[ 'code' => 'BHR', 'continent' => 2, 'code2' => 'BH', ],
			[ 'code' => 'BHS', 'continent' => 3, 'code2' => 'BS', ],
			[ 'code' => 'BIH', 'continent' => 5, 'code2' => 'BA', ],
			[ 'code' => 'BLR', 'continent' => 5, 'code2' => 'BY', ],
			[ 'code' => 'BLZ', 'continent' => 3, 'code2' => 'BZ', ],
			[ 'code' => 'BMU', 'continent' => 3, 'code2' => 'BM', ],
			[ 'code' => 'BOL', 'continent' => 4, 'code2' => 'BO', ],
			[ 'code' => 'BRA', 'continent' => 4, 'code2' => 'BR', ],
			[ 'code' => 'BRB', 'continent' => 3, 'code2' => 'BB', ],
			[ 'code' => 'BRN', 'continent' => 2, 'code2' => 'BN', ],
			[ 'code' => 'BTN', 'continent' => 2, 'code2' => 'BT', ],
			[ 'code' => 'BVT', 'continent' => 7, 'code2' => 'BV', ],
			[ 'code' => 'BWA', 'continent' => 1, 'code2' => 'BW', ],
			[ 'code' => 'CAF', 'continent' => 1, 'code2' => 'CF', ],
			[ 'code' => 'CAN', 'continent' => 3, 'code2' => 'CA', ],
			[ 'code' => 'CCK', 'continent' => 6, 'code2' => 'CC', ],
			[ 'code' => 'CHE', 'continent' => 5, 'code2' => 'CH', ],
			[ 'code' => 'CHL', 'continent' => 4, 'code2' => 'CL', ],
			[ 'code' => 'CHN', 'continent' => 2, 'code2' => 'CN', ],
			[ 'code' => 'CIV', 'continent' => 1, 'code2' => 'CI', ],
			[ 'code' => 'CMR', 'continent' => 1, 'code2' => 'CM', ],
			[ 'code' => 'COD', 'continent' => 1, 'code2' => 'CD', ],
			[ 'code' => 'COG', 'continent' => 1, 'code2' => 'CG', ],
			[ 'code' => 'COK', 'continent' => 6, 'code2' => 'CK', ],
			[ 'code' => 'COL', 'continent' => 4, 'code2' => 'CO', ],
			[ 'code' => 'COM', 'continent' => 1, 'code2' => 'KM', ],
			[ 'code' => 'CPV', 'continent' => 1, 'code2' => 'CV', ],
			[ 'code' => 'CRI', 'continent' => 3, 'code2' => 'CR', ],
			[ 'code' => 'CUB', 'continent' => 3, 'code2' => 'CU', ],
			[ 'code' => 'CXR', 'continent' => 6, 'code2' => 'CX', ],
			[ 'code' => 'CYM', 'continent' => 3, 'code2' => 'KY', ],
			[ 'code' => 'CYP', 'continent' => 2, 'code2' => 'CY', ],
			[ 'code' => 'CZE', 'continent' => 5, 'code2' => 'CZ', ],
			[ 'code' => 'DEU', 'continent' => 5, 'code2' => 'DE', ],
			[ 'code' => 'DJI', 'continent' => 1, 'code2' => 'DJ', ],
			[ 'code' => 'DMA', 'continent' => 3, 'code2' => 'DM', ],
			[ 'code' => 'DNK', 'continent' => 5, 'code2' => 'DK', ],
			[ 'code' => 'DOM', 'continent' => 3, 'code2' => 'DO', ],
			[ 'code' => 'DZA', 'continent' => 1, 'code2' => 'DZ', ],
			[ 'code' => 'ECU', 'continent' => 4, 'code2' => 'EC', ],
			[ 'code' => 'EGY', 'continent' => 1, 'code2' => 'EG', ],
			[ 'code' => 'ERI', 'continent' => 1, 'code2' => 'ER', ],
			[ 'code' => 'ESH', 'continent' => 1, 'code2' => 'EH', ],
			[ 'code' => 'ESP', 'continent' => 5, 'code2' => 'ES', ],
			[ 'code' => 'EST', 'continent' => 5, 'code2' => 'EE', ],
			[ 'code' => 'ETH', 'continent' => 1, 'code2' => 'ET', ],
			[ 'code' => 'FIN', 'continent' => 5, 'code2' => 'FI', ],
			[ 'code' => 'FJI', 'continent' => 6, 'code2' => 'FJ', ],
			[ 'code' => 'FLK', 'continent' => 4, 'code2' => 'FK', ],
			[ 'code' => 'FRA', 'continent' => 5, 'code2' => 'FR', ],
			[ 'code' => 'FRO', 'continent' => 5, 'code2' => 'FO', ],
			[ 'code' => 'FSM', 'continent' => 6, 'code2' => 'FM', ],
			[ 'code' => 'GAB', 'continent' => 1, 'code2' => 'GA', ],
			[ 'code' => 'GBR', 'continent' => 5, 'code2' => 'GB', ],
			[ 'code' => 'GEO', 'continent' => 2, 'code2' => 'GE', ],
			[ 'code' => 'GHA', 'continent' => 1, 'code2' => 'GH', ],
			[ 'code' => 'GIB', 'continent' => 5, 'code2' => 'GI', ],
			[ 'code' => 'GIN', 'continent' => 1, 'code2' => 'GN', ],
			[ 'code' => 'GLP', 'continent' => 3, 'code2' => 'GP', ],
			[ 'code' => 'GMB', 'continent' => 1, 'code2' => 'GM', ],
			[ 'code' => 'GNB', 'continent' => 1, 'code2' => 'GW', ],
			[ 'code' => 'GNQ', 'continent' => 1, 'code2' => 'GQ', ],
			[ 'code' => 'GRC', 'continent' => 5, 'code2' => 'GR', ],
			[ 'code' => 'GRD', 'continent' => 3, 'code2' => 'GD', ],
			[ 'code' => 'GRL', 'continent' => 3, 'code2' => 'GL', ],
			[ 'code' => 'GTM', 'continent' => 3, 'code2' => 'GT', ],
			[ 'code' => 'GUF', 'continent' => 4, 'code2' => 'GF', ],
			[ 'code' => 'GUM', 'continent' => 6, 'code2' => 'GU', ],
			[ 'code' => 'GUY', 'continent' => 4, 'code2' => 'GY', ],
			[ 'code' => 'HKG', 'continent' => 2, 'code2' => 'HK', ],
			[ 'code' => 'HMD', 'continent' => 7, 'code2' => 'HM', ],
			[ 'code' => 'HND', 'continent' => 3, 'code2' => 'HN', ],
			[ 'code' => 'HRV', 'continent' => 5, 'code2' => 'HR', ],
			[ 'code' => 'HTI', 'continent' => 3, 'code2' => 'HT', ],
			[ 'code' => 'HUN', 'continent' => 5, 'code2' => 'HU', ],
			[ 'code' => 'IDN', 'continent' => 2, 'code2' => 'ID', ],
			[ 'code' => 'IND', 'continent' => 2, 'code2' => 'IN', ],
			[ 'code' => 'IOT', 'continent' => 1, 'code2' => 'IO', ],
			[ 'code' => 'IRL', 'continent' => 5, 'code2' => 'IE', ],
			[ 'code' => 'IRN', 'continent' => 2, 'code2' => 'IR', ],
			[ 'code' => 'IRQ', 'continent' => 2, 'code2' => 'IQ', ],
			[ 'code' => 'ISL', 'continent' => 5, 'code2' => 'IS', ],
			[ 'code' => 'ISR', 'continent' => 2, 'code2' => 'IL', ],
			[ 'code' => 'ITA', 'continent' => 5, 'code2' => 'IT', ],
			[ 'code' => 'JAM', 'continent' => 3, 'code2' => 'JM', ],
			[ 'code' => 'JOR', 'continent' => 2, 'code2' => 'JO', ],
			[ 'code' => 'JPN', 'continent' => 2, 'code2' => 'JP', ],
			[ 'code' => 'KAZ', 'continent' => 2, 'code2' => 'KZ', ],
			[ 'code' => 'KEN', 'continent' => 1, 'code2' => 'KE', ],
			[ 'code' => 'KGZ', 'continent' => 2, 'code2' => 'KG', ],
			[ 'code' => 'KHM', 'continent' => 2, 'code2' => 'KH', ],
			[ 'code' => 'KIR', 'continent' => 6, 'code2' => 'KI', ],
			[ 'code' => 'KNA', 'continent' => 3, 'code2' => 'KN', ],
			[ 'code' => 'KOR', 'continent' => 2, 'code2' => 'KR', ],
			[ 'code' => 'KWT', 'continent' => 2, 'code2' => 'KW', ],
			[ 'code' => 'LAO', 'continent' => 2, 'code2' => 'LA', ],
			[ 'code' => 'LBN', 'continent' => 2, 'code2' => 'LB', ],
			[ 'code' => 'LBR', 'continent' => 1, 'code2' => 'LR', ],
			[ 'code' => 'LBY', 'continent' => 1, 'code2' => 'LY', ],
			[ 'code' => 'LCA', 'continent' => 3, 'code2' => 'LC', ],
			[ 'code' => 'LIE', 'continent' => 5, 'code2' => 'LI', ],
			[ 'code' => 'LKA', 'continent' => 2, 'code2' => 'LK', ],
			[ 'code' => 'LSO', 'continent' => 1, 'code2' => 'LS', ],
			[ 'code' => 'LTU', 'continent' => 5, 'code2' => 'LT', ],
			[ 'code' => 'LUX', 'continent' => 5, 'code2' => 'LU', ],
			[ 'code' => 'LVA', 'continent' => 5, 'code2' => 'LV', ],
			[ 'code' => 'MAC', 'continent' => 2, 'code2' => 'MO', ],
			[ 'code' => 'MAR', 'continent' => 1, 'code2' => 'MA', ],
			[ 'code' => 'MCO', 'continent' => 5, 'code2' => 'MC', ],
			[ 'code' => 'MDA', 'continent' => 5, 'code2' => 'MD', ],
			[ 'code' => 'MDG', 'continent' => 1, 'code2' => 'MG', ],
			[ 'code' => 'MDV', 'continent' => 2, 'code2' => 'MV', ],
			[ 'code' => 'MEX', 'continent' => 3, 'code2' => 'MX', ],
			[ 'code' => 'MHL', 'continent' => 6, 'code2' => 'MH', ],
			[ 'code' => 'MKD', 'continent' => 5, 'code2' => 'MK', ],
			[ 'code' => 'MLI', 'continent' => 1, 'code2' => 'ML', ],
			[ 'code' => 'MLT', 'continent' => 5, 'code2' => 'MT', ],
			[ 'code' => 'MMR', 'continent' => 2, 'code2' => 'MM', ],
			[ 'code' => 'MNG', 'continent' => 2, 'code2' => 'MN', ],
			[ 'code' => 'MNP', 'continent' => 6, 'code2' => 'MP', ],
			[ 'code' => 'MOZ', 'continent' => 1, 'code2' => 'MZ', ],
			[ 'code' => 'MRT', 'continent' => 1, 'code2' => 'MR', ],
			[ 'code' => 'MSR', 'continent' => 3, 'code2' => 'MS', ],
			[ 'code' => 'MTQ', 'continent' => 3, 'code2' => 'MQ', ],
			[ 'code' => 'MUS', 'continent' => 1, 'code2' => 'MU', ],
			[ 'code' => 'MWI', 'continent' => 1, 'code2' => 'MW', ],
			[ 'code' => 'MYS', 'continent' => 2, 'code2' => 'MY', ],
			[ 'code' => 'MYT', 'continent' => 1, 'code2' => 'YT', ],
			[ 'code' => 'NAM', 'continent' => 1, 'code2' => 'NA', ],
			[ 'code' => 'NCL', 'continent' => 6, 'code2' => 'NC', ],
			[ 'code' => 'NER', 'continent' => 1, 'code2' => 'NE', ],
			[ 'code' => 'NFK', 'continent' => 6, 'code2' => 'NF', ],
			[ 'code' => 'NGA', 'continent' => 1, 'code2' => 'NG', ],
			[ 'code' => 'NIC', 'continent' => 3, 'code2' => 'NI', ],
			[ 'code' => 'NIU', 'continent' => 6, 'code2' => 'NU', ],
			[ 'code' => 'NLD', 'continent' => 5, 'code2' => 'NL', ],
			[ 'code' => 'NOR', 'continent' => 5, 'code2' => 'NO', ],
			[ 'code' => 'NPL', 'continent' => 2, 'code2' => 'NP', ],
			[ 'code' => 'NRU', 'continent' => 6, 'code2' => 'NR', ],
			[ 'code' => 'NZL', 'continent' => 6, 'code2' => 'NZ', ],
			[ 'code' => 'OMN', 'continent' => 2, 'code2' => 'OM', ],
			[ 'code' => 'PAK', 'continent' => 2, 'code2' => 'PK', ],
			[ 'code' => 'PAN', 'continent' => 3, 'code2' => 'PA', ],
			[ 'code' => 'PCN', 'continent' => 6, 'code2' => 'PN', ],
			[ 'code' => 'PER', 'continent' => 4, 'code2' => 'PE', ],
			[ 'code' => 'PHL', 'continent' => 2, 'code2' => 'PH', ],
			[ 'code' => 'PLW', 'continent' => 6, 'code2' => 'PW', ],
			[ 'code' => 'PNG', 'continent' => 6, 'code2' => 'PG', ],
			[ 'code' => 'POL', 'continent' => 5, 'code2' => 'PL', ],
			[ 'code' => 'PRI', 'continent' => 3, 'code2' => 'PR', ],
			[ 'code' => 'PRK', 'continent' => 2, 'code2' => 'KP', ],
			[ 'code' => 'PRT', 'continent' => 5, 'code2' => 'PT', ],
			[ 'code' => 'PRY', 'continent' => 4, 'code2' => 'PY', ],
			[ 'code' => 'PSE', 'continent' => 2, 'code2' => 'PS', ],
			[ 'code' => 'PYF', 'continent' => 6, 'code2' => 'PF', ],
			[ 'code' => 'QAT', 'continent' => 2, 'code2' => 'QA', ],
			[ 'code' => 'REU', 'continent' => 1, 'code2' => 'RE', ],
			[ 'code' => 'ROM', 'continent' => 5, 'code2' => 'RO', ],
			[ 'code' => 'RUS', 'continent' => 5, 'code2' => 'RU', ],
			[ 'code' => 'RWA', 'continent' => 1, 'code2' => 'RW', ],
			[ 'code' => 'SAU', 'continent' => 2, 'code2' => 'SA', ],
			[ 'code' => 'SDN', 'continent' => 1, 'code2' => 'SD', ],
			[ 'code' => 'SEN', 'continent' => 1, 'code2' => 'SN', ],
			[ 'code' => 'SGP', 'continent' => 2, 'code2' => 'SG', ],
			[ 'code' => 'SGS', 'continent' => 7, 'code2' => 'GS', ],
			[ 'code' => 'SHN', 'continent' => 1, 'code2' => 'SH', ],
			[ 'code' => 'SJM', 'continent' => 5, 'code2' => 'SJ', ],
			[ 'code' => 'SLB', 'continent' => 6, 'code2' => 'SB', ],
			[ 'code' => 'SLE', 'continent' => 1, 'code2' => 'SL', ],
			[ 'code' => 'SLV', 'continent' => 3, 'code2' => 'SV', ],
			[ 'code' => 'SMR', 'continent' => 5, 'code2' => 'SM', ],
			[ 'code' => 'SOM', 'continent' => 1, 'code2' => 'SO', ],
			[ 'code' => 'SPM', 'continent' => 3, 'code2' => 'PM', ],
			[ 'code' => 'STP', 'continent' => 1, 'code2' => 'ST', ],
			[ 'code' => 'SUR', 'continent' => 4, 'code2' => 'SR', ],
			[ 'code' => 'SVK', 'continent' => 5, 'code2' => 'SK', ],
			[ 'code' => 'SVN', 'continent' => 5, 'code2' => 'SI', ],
			[ 'code' => 'SWE', 'continent' => 5, 'code2' => 'SE', ],
			[ 'code' => 'SWZ', 'continent' => 1, 'code2' => 'SZ', ],
			[ 'code' => 'SYC', 'continent' => 1, 'code2' => 'SC', ],
			[ 'code' => 'SYR', 'continent' => 2, 'code2' => 'SY', ],
			[ 'code' => 'TCA', 'continent' => 3, 'code2' => 'TC', ],
			[ 'code' => 'TCD', 'continent' => 1, 'code2' => 'TD', ],
			[ 'code' => 'TGO', 'continent' => 1, 'code2' => 'TG', ],
			[ 'code' => 'THA', 'continent' => 2, 'code2' => 'TH', ],
			[ 'code' => 'TJK', 'continent' => 2, 'code2' => 'TJ', ],
			[ 'code' => 'TKL', 'continent' => 6, 'code2' => 'TK', ],
			[ 'code' => 'TKM', 'continent' => 2, 'code2' => 'TM', ],
			[ 'code' => 'TMP', 'continent' => 2, 'code2' => 'TP', ],
			[ 'code' => 'TON', 'continent' => 6, 'code2' => 'TO', ],
			[ 'code' => 'TTO', 'continent' => 3, 'code2' => 'TT', ],
			[ 'code' => 'TUN', 'continent' => 1, 'code2' => 'TN', ],
			[ 'code' => 'TUR', 'continent' => 2, 'code2' => 'TR', ],
			[ 'code' => 'TUV', 'continent' => 6, 'code2' => 'TV', ],
			[ 'code' => 'TWN', 'continent' => 2, 'code2' => 'TW', ],
			[ 'code' => 'TZA', 'continent' => 1, 'code2' => 'TZ', ],
			[ 'code' => 'UGA', 'continent' => 1, 'code2' => 'UG', ],
			[ 'code' => 'UKR', 'continent' => 5, 'code2' => 'UA', ],
			[ 'code' => 'UMI', 'continent' => 6, 'code2' => 'UM', ],
			[ 'code' => 'URY', 'continent' => 4, 'code2' => 'UY', ],
			[ 'code' => 'USA', 'continent' => 3, 'code2' => 'US', ],
			[ 'code' => 'UZB', 'continent' => 2, 'code2' => 'UZ', ],
			[ 'code' => 'VAT', 'continent' => 5, 'code2' => 'VA', ],
			[ 'code' => 'VCT', 'continent' => 3, 'code2' => 'VC', ],
			[ 'code' => 'VEN', 'continent' => 4, 'code2' => 'VE', ],
			[ 'code' => 'VGB', 'continent' => 3, 'code2' => 'VG', ],
			[ 'code' => 'VIR', 'continent' => 3, 'code2' => 'VI', ],
			[ 'code' => 'VNM', 'continent' => 2, 'code2' => 'VN', ],
			[ 'code' => 'VUT', 'continent' => 6, 'code2' => 'VU', ],
			[ 'code' => 'WLF', 'continent' => 6, 'code2' => 'WF', ],
			[ 'code' => 'WSM', 'continent' => 6, 'code2' => 'WS', ],
			[ 'code' => 'YEM', 'continent' => 2, 'code2' => 'YE', ],
			[ 'code' => 'YUG', 'continent' => 5, 'code2' => 'YU', ],
			[ 'code' => 'ZAF', 'continent' => 1, 'code2' => 'ZA', ],
			[ 'code' => 'ZMB', 'continent' => 1, 'code2' => 'ZM', ],
			[ 'code' => 'ZWE', 'continent' => 1, 'code2' => 'ZW', ],
		];

		\DB::table('country')->insert($countries);


		\DB::table('country_translations')->delete();
		$country_translations = [
			[ 'country_id' => 1, 'locale' => 'en', 'name' => 'Aruba',],
			[ 'country_id' => 2, 'locale' => 'en', 'name' => 'Afghanistan',],
			[ 'country_id' => 3, 'locale' => 'en', 'name' => 'Angola',],
			[ 'country_id' => 4, 'locale' => 'en', 'name' => 'Anguilla', ],
			[ 'country_id' => 5, 'locale' => 'en', 'name' => 'Albania', ],
			[ 'country_id' => 6, 'locale' => 'en', 'name' => 'Andorra', ],
			[ 'country_id' => 7, 'locale' => 'en', 'name' => 'Netherlands Antilles', ],
			[ 'country_id' => 8, 'locale' => 'en', 'name' => 'United Arab Emirates', ],
			[ 'country_id' => 9, 'locale' => 'en', 'name' => 'Argentina', ],
			[ 'country_id' => 10, 'locale' => 'en', 'name' => 'Armenia', ],
			[ 'country_id' => 11, 'locale' => 'en', 'name' => 'American Samoa', ],
			[ 'country_id' => 12, 'locale' => 'en', 'name' => 'Antarctica', ],
			[ 'country_id' => 13, 'locale' => 'en', 'name' => 'French Southern territories',],
			[ 'country_id' => 14, 'locale' => 'en', 'name' => 'Antigua and Barbuda', ],
			[ 'country_id' => 15, 'locale' => 'en', 'name' => 'Australia', ],
			[ 'country_id' => 16, 'locale' => 'en', 'name' => 'Austria', ],
			[ 'country_id' => 17, 'locale' => 'en', 'name' => 'Azerbaijan', ],
			[ 'country_id' => 18, 'locale' => 'en', 'name' => 'Burundi', ],
			[ 'country_id' => 19, 'locale' => 'en', 'name' => 'Belgium', ],
			[ 'country_id' => 20, 'locale' => 'en', 'name' => 'Benin', ],
			[ 'country_id' => 21, 'locale' => 'en', 'name' => 'Burkina Faso', ],
			[ 'country_id' => 22, 'locale' => 'en', 'name' => 'Bangladesh', ],
			[ 'country_id' => 23, 'locale' => 'en', 'name' => 'Bulgaria', ],
			[ 'country_id' => 24, 'locale' => 'en', 'name' => 'Bahrain', ],
			[ 'country_id' => 25, 'locale' => 'en', 'name' => 'Bahamas', ],
			[ 'country_id' => 26, 'locale' => 'en', 'name' => 'Bosnia and Herzegovina', ],
			[ 'country_id' => 27, 'locale' => 'en', 'name' => 'Belarus', ],
			[ 'country_id' => 28, 'locale' => 'en', 'name' => 'Belize', ],
			[ 'country_id' => 29, 'locale' => 'en', 'name' => 'Bermuda', ],
			[ 'country_id' => 30, 'locale' => 'en', 'name' => 'Bolivia', ],
			[ 'country_id' => 31, 'locale' => 'en', 'name' => 'Brazil', ],
			[ 'country_id' => 32, 'locale' => 'en', 'name' => 'Barbados', ],
			[ 'country_id' => 33, 'locale' => 'en', 'name' => 'Brunei', ],
			[ 'country_id' => 34, 'locale' => 'en', 'name' => 'Bhutan', ],
			[ 'country_id' => 35, 'locale' => 'en', 'name' => 'Bouvet Island', ],
			[ 'country_id' => 36, 'locale' => 'en', 'name' => 'Botswana', ],
			[ 'country_id' => 37, 'locale' => 'en', 'name' => 'Central African Republic', ],
			[ 'country_id' => 38, 'locale' => 'en', 'name' => 'Canada', ],
			[ 'country_id' => 39, 'locale' => 'en', 'name' => 'Cocos (Keeling) Islands', ],
			[ 'country_id' => 40, 'locale' => 'en', 'name' => 'Switzerland', ],
			[ 'country_id' => 41, 'locale' => 'en', 'name' => 'Chile', ],
			[ 'country_id' => 42, 'locale' => 'en', 'name' => 'China', ],
			[ 'country_id' => 43, 'locale' => 'en', 'name' => 'Côte d’Ivoire', ],
			[ 'country_id' => 44, 'locale' => 'en', 'name' => 'Cameroon', ],
			[ 'country_id' => 45, 'locale' => 'en', 'name' => 'Congo, The Democratic Republic of the', ],
			[ 'country_id' => 46, 'locale' => 'en', 'name' => 'Congo', ],
			[ 'country_id' => 47, 'locale' => 'en', 'name' => 'Cook Islands', ],
			[ 'country_id' => 48, 'locale' => 'en', 'name' => 'Colombia', ],
			[ 'country_id' => 49, 'locale' => 'en', 'name' => 'Comoros', ],
			[ 'country_id' => 50, 'locale' => 'en', 'name' => 'Cape Verde', ],
			[ 'country_id' => 51, 'locale' => 'en', 'name' => 'Costa Rica', ],
			[ 'country_id' => 52, 'locale' => 'en', 'name' => 'Cuba', ],
			[ 'country_id' => 53, 'locale' => 'en', 'name' => 'Christmas Island', ],
			[ 'country_id' => 54, 'locale' => 'en', 'name' => 'Cayman Islands', ],
			[ 'country_id' => 55, 'locale' => 'en', 'name' => 'Cyprus', ],
			[ 'country_id' => 56, 'locale' => 'en','name' => 'Czech Republic', ],
			[ 'country_id' => 57, 'locale' => 'en', 'name' => 'Germany', ],
			[ 'country_id' => 58, 'locale' => 'en', 'name' => 'Djibouti', ],
			[ 'country_id' => 59, 'locale' => 'en', 'name' => 'Dominica', ],
			[ 'country_id' => 60, 'locale' => 'en', 'name' => 'Denmark', ],
			[ 'country_id' => 61, 'locale' => 'en', 'name' => 'Dominican Republic', ],
			[ 'country_id' => 62, 'locale' => 'en', 'name' => 'Algeria', ],
			[ 'country_id' => 63, 'locale' => 'en', 'name' => 'Ecuador', ],
			[ 'country_id' => 64, 'locale' => 'en', 'name' => 'Egypt', ],
			[ 'country_id' => 65, 'locale' => 'en', 'name' => 'Eritrea',],
			[ 'country_id' => 66, 'locale' => 'en', 'name' => 'Western Sahara',],
			[ 'country_id' => 67, 'locale' => 'en', 'name' => 'Spain', ],
			[ 'country_id' => 68, 'locale' => 'en', 'name' => 'Estonia', ],
			[ 'country_id' => 69, 'locale' => 'en', 'name' => 'Ethiopia', ],
			[ 'country_id' => 70, 'locale' => 'en', 'name' => 'Finland', ],
			[ 'country_id' => 71, 'locale' => 'en', 'name' => 'Fiji Islands', ],
			[ 'country_id' => 72, 'locale' => 'en', 'name' => 'Falkland Islands', ],
			[ 'country_id' => 73, 'locale' => 'en', 'name' => 'France', ],
			[ 'country_id' => 74, 'locale' => 'en', 'name' => 'Faroe Islands', ],
			[ 'country_id' => 75, 'locale' => 'en', 'name' => 'Micronesia, Federated States of', ],
			[ 'country_id' => 76, 'locale' => 'en', 'name' => 'Gabon', ],
			[ 'country_id' => 77, 'locale' => 'en', 'name' => 'United Kingdom', ],
			[ 'country_id' => 78, 'locale' => 'en', 'name' => 'Georgia', ],
			[ 'country_id' => 79, 'locale' => 'en', 'name' => 'Ghana', ],
			[ 'country_id' => 80, 'locale' => 'en', 'name' => 'Gibraltar', ],
			[ 'country_id' => 81, 'locale' => 'en', 'name' => 'Guinea', ],
			[ 'country_id' => 82, 'locale' => 'en', 'name' => 'Guadeloupe', ],
			[ 'country_id' => 83, 'locale' => 'en', 'name' => 'Gambia', ],
			[ 'country_id' => 84, 'locale' => 'en', 'name' => 'Guinea-Bissau', ],
			[ 'country_id' => 85, 'locale' => 'en', 'name' => 'Equatorial Guinea', ],
			[ 'country_id' => 86, 'locale' => 'en', 'name' => 'Greece', ],
			[ 'country_id' => 87, 'locale' => 'en', 'name' => 'Grenada', ],
			[ 'country_id' => 88, 'locale' => 'en', 'name' => 'Greenland', ],
			[ 'country_id' => 89, 'locale' => 'en', 'name' => 'Guatemala', ],
			[ 'country_id' => 90, 'locale' => 'en', 'name' => 'French Guiana', ],
			[ 'country_id' => 91, 'locale' => 'en', 'name' => 'Guam', ],
			[ 'country_id' => 92, 'locale' => 'en', 'name' => 'Guyana', ],
			[ 'country_id' => 93, 'locale' => 'en', 'name' => 'Hong Kong', ],
			[ 'country_id' => 94, 'locale' => 'en', 'name' => 'Heard Island and McDonald Islands', ],
			[ 'country_id' => 95, 'locale' => 'en', 'name' => 'Honduras', ],
			[ 'country_id' => 96, 'locale' => 'en', 'name' => 'Croatia', ],
			[ 'country_id' => 97, 'locale' => 'en', 'name' => 'Haiti', ],
			[ 'country_id' => 98, 'locale' => 'en', 'name' => 'Hungary', ],
			[ 'country_id' => 99, 'locale' => 'en', 'name' => 'Indonesia', ],
			[ 'country_id' => 100, 'locale' => 'en', 'name' => 'India', ],
			[ 'country_id' => 101, 'locale' => 'en', 'name' => 'British Indian Ocean Territory', ],
			[ 'country_id' => 102, 'locale' => 'en', 'name' => 'Ireland', ],
			[ 'country_id' => 103, 'locale' => 'en', 'name' => 'Iran', ],
			[ 'country_id' => 104, 'locale' => 'en', 'name' => 'Iraq', ],
			[ 'country_id' => 105, 'locale' => 'en', 'name' => 'Iceland', ],
			[ 'country_id' => 106, 'locale' => 'en', 'name' => 'Israel', ],
			[ 'country_id' => 107, 'locale' => 'en', 'name' => 'Italy', ],
			[ 'country_id' => 108, 'locale' => 'en', 'name' => 'Jamaica', ],
			[ 'country_id' => 109, 'locale' => 'en', 'name' => 'Jordan', ],
			[ 'country_id' => 110, 'locale' => 'en', 'name' => 'Japan', ],
			[ 'country_id' => 111, 'locale' => 'en', 'name' => 'Kazakstan', ],
			[ 'country_id' => 112, 'locale' => 'en', 'name' => 'Kenya', ],
			[ 'country_id' => 113, 'locale' => 'en', 'name' => 'Kyrgyzstan', ],
			[ 'country_id' => 114, 'locale' => 'en', 'name' => 'Cambodia', ],
			[ 'country_id' => 115, 'locale' => 'en', 'name' => 'Kiribati', ],
			[ 'country_id' => 116, 'locale' => 'en', 'name' => 'Saint Kitts and Nevis', ],
			[ 'country_id' => 117, 'locale' => 'en', 'name' => 'South Korea', ],
			[ 'country_id' => 118, 'locale' => 'en', 'name' => 'Kuwait', ],
			[ 'country_id' => 119, 'locale' => 'en', 'name' => 'Laos', ],
			[ 'country_id' => 120, 'locale' => 'en', 'name' => 'Lebanon', ],
			[ 'country_id' => 121, 'locale' => 'en', 'name' => 'Liberia', ],
			[ 'country_id' => 122, 'locale' => 'en', 'name' => 'Libyan Arab Jamahiriya', ],
			[ 'country_id' => 123, 'locale' => 'en', 'name' => 'Saint Lucia', ],
			[ 'country_id' => 124, 'locale' => 'en', 'name' => 'Liechtenstein', ],
			[ 'country_id' => 125, 'locale' => 'en', 'name' => 'Sri Lanka', ],
			[ 'country_id' => 126, 'locale' => 'en', 'name' => 'Lesotho', ],
			[ 'country_id' => 127, 'locale' => 'en', 'name' => 'Lithuania', ],
			[ 'country_id' => 128, 'locale' => 'en', 'name' => 'Luxembourg', ],
			[ 'country_id' => 129, 'locale' => 'en', 'name' => 'Latvia', ],
			[ 'country_id' => 130, 'locale' => 'en', 'name' => 'Macao', ],
			[ 'country_id' => 131, 'locale' => 'en', 'name' => 'Morocco', ],
			[ 'country_id' => 132, 'locale' => 'en', 'name' => 'Monaco', ],
			[ 'country_id' => 133, 'locale' => 'en', 'name' => 'Moldova', ],
			[ 'country_id' => 134, 'locale' => 'en', 'name' => 'Madagascar', ],
			[ 'country_id' => 135, 'locale' => 'en', 'name' => 'Maldives', ],
			[ 'country_id' => 136, 'locale' => 'en', 'name' => 'Mexico', ],
			[ 'country_id' => 137, 'locale' => 'en', 'name' => 'Marshall Islands', ],
			[ 'country_id' => 138, 'locale' => 'en', 'name' => 'Macedonia', ],
			[ 'country_id' => 139, 'locale' => 'en', 'name' => 'Mali', ],
			[ 'country_id' => 140, 'locale' => 'en', 'name' => 'Malta', ],
			[ 'country_id' => 141, 'locale' => 'en', 'name' => 'Myanmar', ],
			[ 'country_id' => 142, 'locale' => 'en', 'name' => 'Mongolia', ],
			[ 'country_id' => 143, 'locale' => 'en', 'name' => 'Northern Mariana Islands', ],
			[ 'country_id' => 144, 'locale' => 'en', 'name' => 'Mozambique', ],
			[ 'country_id' => 145, 'locale' => 'en', 'name' => 'Mauritania', ],
			[ 'country_id' => 146, 'locale' => 'en', 'name' => 'Montserrat', ],
			[ 'country_id' => 147, 'locale' => 'en', 'name' => 'Martinique', ],
			[ 'country_id' => 148, 'locale' => 'en', 'name' => 'Mauritius', ],
			[ 'country_id' => 149, 'locale' => 'en', 'name' => 'Malawi', ],
			[ 'country_id' => 150, 'locale' => 'en', 'name' => 'Malaysia', ],
			[ 'country_id' => 151, 'locale' => 'en', 'name' => 'Mayotte', ],
			[ 'country_id' => 152, 'locale' => 'en', 'name' => 'Namibia', ],
			[ 'country_id' => 153, 'locale' => 'en', 'name' => 'New Caledonia', ],
			[ 'country_id' => 154, 'locale' => 'en', 'name' => 'Niger', ],
			[ 'country_id' => 155, 'locale' => 'en', 'name' => 'Norfolk Island', ],
			[ 'country_id' => 156, 'locale' => 'en', 'name' => 'Nigeria', ],
			[ 'country_id' => 157, 'locale' => 'en', 'name' => 'Nicaragua', ],
			[ 'country_id' => 158, 'locale' => 'en', 'name' => 'Niue', ],
			[ 'country_id' => 159, 'locale' => 'en', 'name' => 'Netherlands', ],
			[ 'country_id' => 160, 'locale' => 'en', 'name' => 'Norway', ],
			[ 'country_id' => 161, 'locale' => 'en', 'name' => 'Nepal', ],
			[ 'country_id' => 162, 'locale' => 'en', 'name' => 'Nauru', ],
			[ 'country_id' => 163, 'locale' => 'en', 'name' => 'New Zealand', ],
			[ 'country_id' => 164, 'locale' => 'en', 'name' => 'Oman', ],
			[ 'country_id' => 165, 'locale' => 'en', 'name' => 'Pakistan', ],
			[ 'country_id' => 166, 'locale' => 'en', 'name' => 'Panama', ],
			[ 'country_id' => 167, 'locale' => 'en', 'name' => 'Pitcairn', ],
			[ 'country_id' => 168, 'locale' => 'en', 'name' => 'Peru', ],
			[ 'country_id' => 169, 'locale' => 'en', 'name' => 'Philippines', ],
			[ 'country_id' => 170, 'locale' => 'en', 'name' => 'Palau', ],
			[ 'country_id' => 171, 'locale' => 'en', 'name' => 'Papua New Guinea', ],
			[ 'country_id' => 172, 'locale' => 'en', 'name' => 'Poland', ],
			[ 'country_id' => 173, 'locale' => 'en', 'name' => 'Puerto Rico', ],
			[ 'country_id' => 174, 'locale' => 'en', 'name' => 'North Korea', ],
			[ 'country_id' => 175, 'locale' => 'en', 'name' => 'Portugal', ],
			[ 'country_id' => 176, 'locale' => 'en', 'name' => 'Paraguay', ],
			[ 'country_id' => 177, 'locale' => 'en', 'name' => 'Palestine', ],
			[ 'country_id' => 178, 'locale' => 'en', 'name' => 'French Polynesia', ],
			[ 'country_id' => 179, 'locale' => 'en', 'name' => 'Qatar', ],
			[ 'country_id' => 180, 'locale' => 'en', 'name' => 'Réunion', ],
			[ 'country_id' => 181, 'locale' => 'en', 'name' => 'Romania', ],
			[ 'country_id' => 182, 'locale' => 'en', 'name' => 'Russian Federation', ],
			[ 'country_id' => 183, 'locale' => 'en', 'name' => 'Rwanda', ],
			[ 'country_id' => 184, 'locale' => 'en', 'name' => 'Saudi Arabia', ],
			[ 'country_id' => 185, 'locale' => 'en', 'name' => 'Sudan', ],
			[ 'country_id' => 186, 'locale' => 'en', 'name' => 'Senegal', ],
			[ 'country_id' => 187, 'locale' => 'en', 'name' => 'Singapore', ],
			[ 'country_id' => 188, 'locale' => 'en', 'name' => 'South Georgia and the South Sandwich Islands', ],
			[ 'country_id' => 189, 'locale' => 'en', 'name' => 'Saint Helena', ],
			[ 'country_id' => 190, 'locale' => 'en', 'name' => 'Svalbard and Jan Mayen', ],
			[ 'country_id' => 191, 'locale' => 'en', 'name' => 'Solomon Islands', ],
			[ 'country_id' => 192, 'locale' => 'en', 'name' => 'Sierra Leone', ],
			[ 'country_id' => 193, 'locale' => 'en', 'name' => 'El Salvador', ],
			[ 'country_id' => 194, 'locale' => 'en', 'name' => 'San Marino', ],
			[ 'country_id' => 195, 'locale' => 'en', 'name' => 'Somalia', ],
			[ 'country_id' => 196, 'locale' => 'en', 'name' => 'Saint Pierre and Miquelon', ],
			[ 'country_id' => 197, 'locale' => 'en', 'name' => 'Sao Tome and Principe', ],
			[ 'country_id' => 198, 'locale' => 'en', 'name' => 'Suriname', ],
			[ 'country_id' => 199, 'locale' => 'en', 'name' => 'Slovakia', ],
			[ 'country_id' => 200, 'locale' => 'en', 'name' => 'Slovenia', ],
			[ 'country_id' => 201, 'locale' => 'en', 'name' => 'Sweden', ],
			[ 'country_id' => 202, 'locale' => 'en', 'name' => 'Swaziland', ],
			[ 'country_id' => 203, 'locale' => 'en', 'name' => 'Seychelles', ],
			[ 'country_id' => 204, 'locale' => 'en', 'name' => 'Syria', ],
			[ 'country_id' => 205, 'locale' => 'en', 'name' => 'Turks and Caicos Islands', ],
			[ 'country_id' => 206, 'locale' => 'en', 'name' => 'Chad', ],
			[ 'country_id' => 207, 'locale' => 'en', 'name' => 'Togo', ],
			[ 'country_id' => 208, 'locale' => 'en', 'name' => 'Thailand', ],
			[ 'country_id' => 209, 'locale' => 'en', 'name' => 'Tajikistan', ],
			[ 'country_id' => 210, 'locale' => 'en', 'name' => 'Tokelau', ],
			[ 'country_id' => 211, 'locale' => 'en', 'name' => 'Turkmenistan', ],
			[ 'country_id' => 212, 'locale' => 'en', 'name' => 'East Timor', ],
			[ 'country_id' => 213, 'locale' => 'en', 'name' => 'Tonga', ],
			[ 'country_id' => 214, 'locale' => 'en', 'name' => 'Trinidad and Tobago', ],
			[ 'country_id' => 215, 'locale' => 'en', 'name' => 'Tunisia', ],
			[ 'country_id' => 216, 'locale' => 'en', 'name' => 'Turkey', ],
			[ 'country_id' => 217, 'locale' => 'en', 'name' => 'Tuvalu', ],
			[ 'country_id' => 218, 'locale' => 'en', 'name' => 'Taiwan', ],
			[ 'country_id' => 219, 'locale' => 'en', 'name' => 'Tanzania', ],
			[ 'country_id' => 220, 'locale' => 'en', 'name' => 'Uganda', ],
			[ 'country_id' => 221, 'locale' => 'en', 'name' => 'Ukraine', ],
			[ 'country_id' => 222, 'locale' => 'en', 'name' => 'United States Minor Outlying Islands', ],
			[ 'country_id' => 223, 'locale' => 'en', 'name' => 'Uruguay', ],
			[ 'country_id' => 224, 'locale' => 'en', 'name' => 'United States', ],
			[ 'country_id' => 225, 'locale' => 'en', 'name' => 'Uzbekistan', ],
			[ 'country_id' => 226, 'locale' => 'en', 'name' => 'Holy See (Vatican City State)', ],
			[ 'country_id' => 227, 'locale' => 'en', 'name' => 'Saint Vincent and the Grenadines', ],
			[ 'country_id' => 228, 'locale' => 'en', 'name' => 'Venezuela', ],
			[ 'country_id' => 229, 'locale' => 'en', 'name' => 'Virgin Islands, British', ],
			[ 'country_id' => 230, 'locale' => 'en', 'name' => 'Virgin Islands, U.S.', ],
			[ 'country_id' => 231, 'locale' => 'en', 'name' => 'Vietnam', ],
			[ 'country_id' => 232, 'locale' => 'en', 'name' => 'Vanuatu', ],
			[ 'country_id' => 233, 'locale' => 'en', 'name' => 'Wallis and Futuna', ],
			[ 'country_id' => 234, 'locale' => 'en', 'name' => 'Samoa', ],
			[ 'country_id' => 235, 'locale' => 'en', 'name' => 'Yemen', ],
			[ 'country_id' => 236, 'locale' => 'en', 'name' => 'Yugoslavia', ],
			[ 'country_id' => 237, 'locale' => 'en', 'name' => 'South Africa', ],
			[ 'country_id' => 238, 'locale' => 'en', 'name' => 'Zambia', ],
			[ 'country_id' => 239, 'locale' => 'en', 'name' => 'Zimbabwe', ],
		];
		
		\DB::table('country_translations')->insert($country_translations);

	}
}
