<?php
include 'header2.php';
include 'switcher.php';
?>

<style type="text/css">.tt_tabs .tt_timetable .event{background: #ffc000;} .tt_tabs_navigation li a:hover, .tt_tabs_navigation li a.selected, .tt_tabs_navigation li.ui-tabs-active a{border-color:#ffc000 !important;}.tabs_box_navigation.sf-timetable-menu .tabs_box_navigation_selected{background-color:#ffc000;border-color:#ffc000;}.tabs_box_navigation.sf-timetable-menu .tabs_box_navigation_selected:hover{background-color: #FFF; border: 1px solid rgba(0, 0, 0, 0.1);}.sf-timetable-menu li ul li a:hover, .sf-timetable-menu li ul li.selected a:hover{background-color:#ffc000;}</style><link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway:regular&amp;subset="><style type="text/css">.tt_tabs .tt_timetable{font-family:"Raleway" !important;}</style><style type="text/css" data-type="vc_custom-css">.lin-top-icon-1 .aio-icon i{
        padding: 35px;
        border-radius: 50%;
        background-color: #ffc000;
    }
    .lin-top-icon-2 .aio-icon i{
        padding: 35px;
        border-radius: 50%;
        background-color: #2abfd4;
    }
    .lin-classess-icon-1 i{
        padding: 18px;
        border-radius: 50%;
        background-color: #ffc000;
    }
    .lin-classess-icon-2 i{
        padding: 18px;
        border-radius: 50%;
        background-color: #2abfd4;
    }
    .lin-teacher-progress-bar .vc_label {
        color: #FFF;
    }
    .lin-testimonial .testimonial_rotator_slide_title,
    .lin-testimonial .testimonial_rotator_quote {
        color: #fff;
    }
    .lin-testimonial .testimonial_rotator_quote cite{
        color: #ffc000;
    }</style><style type="text/css" data-type="vc_shortcodes-custom-css">.vc_custom_1455372627078{margin-top: -5px !important;padding-top: 0px !important;}.vc_custom_1455026901060{margin-bottom: 0px !important;padding-bottom: 45px !important;}.vc_custom_1454939061687{margin-top: 0px !important;margin-bottom: 50px !important;padding-top: 0px !important;}.vc_custom_1455026924595{padding-top: 35px !important;padding-bottom: 60px !important;background-color: #f5f5f5 !important;}.vc_custom_1455026954346{margin-top: 20px !important;}.vc_custom_1455187949043{margin-bottom: 0px !important;}.vc_custom_1452679369430{padding-top: 0px !important;}.vc_custom_1452679343109{padding-top: 0px !important;}.vc_custom_1452679374327{margin-bottom: 0px !important;padding-top: 0px !important;}.vc_custom_1452601815321{margin-top: 0px !important;margin-bottom: -95px !important;padding-top: 0px !important;}.vc_custom_1454939499838{padding-right: 30px !important;padding-left: 30px !important;}.vc_custom_1454939749285{padding-right: 30px !important;padding-left: 30px !important;}.vc_custom_1454939755940{padding-right: 30px !important;padding-left: 30px !important;}.vc_custom_1455187966970{margin-bottom: 0px !important;}.vc_custom_1455187981301{margin-bottom: 0px !important;}.vc_custom_1449830525402{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;background-color: #ffffff !important;}.vc_custom_1448133329933{margin-top: 0px !important;margin-right: 0px !important;margin-left: 0px !important;background-color: #ffffff !important;}.vc_custom_1448021407279{padding-top: 0px !important;padding-bottom: 0px !important;background-color: rgba(255,255,255,0.01) !important;*background-color: rgb(255,255,255) !important;}.vc_custom_1452239139754{padding-top: 0px !important;}.vc_custom_1452239211225{padding-top: 0px !important;}.vc_custom_1448021407279{padding-top: 0px !important;padding-bottom: 0px !important;background-color: rgba(255,255,255,0.01) !important;*background-color: rgb(255,255,255) !important;}.vc_custom_1452239258977{padding-top: 0px !important;}.vc_custom_1452601914831{margin-bottom: 0px !important;padding-top: 0px !important;}.vc_custom_1454593299044{margin-top: 10px !important;margin-left: 10px !important;}.vc_custom_1449311566289{margin-top: 10px !important;margin-left: 10px !important;}.vc_custom_1449311580048{margin-top: 10px !important;margin-left: 10px !important;}.vc_custom_1449311592170{margin-top: 10px !important;margin-left: 10px !important;}</style><noscript><style type="text/css"> .wpb_animate_when_almost_visible { opacity: 1; }</style></noscript>

    <div class="cbp-row wh-page-title-bar">
        <div class="cbp-container">
            <div class="one whole wh-padding wh-page-title-wrapper">
                <h1 class="page-title">Services</h1>
                <div class="wh-breadcrumbs align-left">
                    <nav aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
                        <ul class="trail-items" itemscope itemtype="http://schema.org/BreadcrumbList">
                            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"
                                class="trail-item trail-begin"><a href="http://skilled.aislinthemes.com"
                                                                  rel="home"><span
                                        itemprop="name">Home</span></a>
                                <meta itemprop="position" content="1"/>
                            </li>
                            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"
                                class="trail-item trail-end"><span itemprop="name">Services</span>
                                <meta itemprop="position" content="2"/>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

<div class="cbp-row wh-content">
    <div class="cbp-container">
        <div class="entry-content one whole wh-padding">
            <div class="vc_row wpb_row vc_row-fluid vc_custom_1455372627078"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner vc_custom_1455187949043"><div class="wpb_wrapper"><div id="ultimate-heading-6883574122314fb59" class="uvc-heading ult-adjust-bottom-margin ultimate-heading-6883574122314fb59 uvc-2155 " data-hspacer="no_spacer" data-halign="center" style="text-align:center"><div class="uvc-heading-spacer no_spacer" style="top"></div><div class="uvc-main-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-6883574122314fb59 h2" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:26px;&quot;,&quot;line-height&quot;:&quot;desktop:45px;&quot;}"><h2 style="font-family:'Raleway';font-weight:900;color:#333333;margin-bottom:20px;">A SMARTER WAY TO STUDY</h2></div></div><div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_100 vc_sep_pos_align_center vc_separator_no_text vc_sep_color_grey  lin-vc-separator"><span class="vc_sep_holder vc_sep_holder_l"><span class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span class="vc_sep_line"></span></span>
                            </div></div></div></div></div><div data-vc-full-width="true" data-vc-full-width-init="true" class="vc_row wpb_row vc_row-fluid vc_custom_1455026901060" style="position: relative; left: -58px; box-sizing: border-box; width: 1286px; padding-left: 58px; padding-right: 58px;"><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452679369430"><div class="wpb_wrapper"><div class="aio-icon-component   lin-classess-icon-1 style_1"><div id="Info-box-wrap-3991" class="aio-icon-box left-icon" style=""><div class="aio-icon-left"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                <div class="aio-icon advanced  animated bounceInLeft delay-03" data-animation="bounceInLeft" data-animation-delay="03" style="color:#ffffff;background:#377bab;border-style:solid;border-color:#ffc000;border-width:6px;width:100px;height:100px;line-height:100px;border-radius:120px;font-size:35px;display:inline-block;">
                                                    <i class="linear-apartment"></i>
                                                </div></div></div></div><div class="aio-ibd-block"><div class="aio-icon-header"><h3 class="aio-icon-title ult-responsive" data-ultimate-target="#Info-box-wrap-3991 .aio-icon-title" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:27px;&quot;}" style="font-family:'Raleway';font-weight:800;color:#333333;">COMMUNITIES</h3></div> <!-- header --><div class="aio-icon-description ult-responsive" data-ultimate-target="#Info-box-wrap-3991 .aio-icon-description" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';color:#717070;"><p>English opens many doors in life and can be your route to a successful future.</p>
                                        </div> <!-- description --></div> <!-- aio-ibd-block --></div> <!-- aio-icon-box --></div> <!-- aio-icon-component --><div class="ult-spacer spacer-57412231514e7" data-id="57412231514e7" data-height="10" data-height-mobile="10" data-height-tab="10" data-height-tab-portrait="" data-height-mobile-landscape="" style="clear:both;display:block;"></div><div class="aio-icon-component   lin-classess-icon-1 style_1"><div id="Info-box-wrap-7262" class="aio-icon-box left-icon" style=""><div class="aio-icon-left"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                <div class="aio-icon advanced  animated bounceInLeft delay-03" data-animation="bounceInLeft" data-animation-delay="03" style="color:#ffffff;background:#377bab;border-style:solid;border-color:#ffc000;border-width:6px;width:100px;height:100px;line-height:100px;border-radius:120px;font-size:35px;display:inline-block;">
                                                    <i class="linear-earth"></i>
                                                </div></div></div></div><div class="aio-ibd-block"><div class="aio-icon-header"><h3 class="aio-icon-title ult-responsive" data-ultimate-target="#Info-box-wrap-7262 .aio-icon-title" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:27px;&quot;}" style="font-family:'Raleway';font-weight:800;color:#333333;">THE WORLD</h3></div> <!-- header --><div class="aio-icon-description ult-responsive" data-ultimate-target="#Info-box-wrap-7262 .aio-icon-description" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';color:#717070;"><p>Understanding of the world develops as children take notice of everything.</p>
                                        </div> <!-- description --></div> <!-- aio-ibd-block --></div> <!-- aio-icon-box --></div> <!-- aio-icon-component --></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452679343109"><div class="wpb_wrapper"><div class="aio-icon-component   lin-classess-icon-1 style_1"><div id="Info-box-wrap-4297" class="aio-icon-box left-icon" style=""><div class="aio-icon-left"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                <div class="aio-icon advanced  animated bounceInLeft delay-03" data-animation="bounceInLeft" data-animation-delay="03" style="color:#ffffff;background:#377bab;border-style:solid;border-color:#ffc000;border-width:6px;width:100px;height:100px;line-height:100px;border-radius:120px;font-size:35px;display:inline-block;">
                                                    <i class="linear-smartphone"></i>
                                                </div></div></div></div><div class="aio-ibd-block"><div class="aio-icon-header"><h3 class="aio-icon-title ult-responsive" data-ultimate-target="#Info-box-wrap-4297 .aio-icon-title" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:27px;&quot;}" style="font-family:'Raleway';font-weight:800;color:#333333;">TECHNOLOGY</h3></div> <!-- header --><div class="aio-icon-description ult-responsive" data-ultimate-target="#Info-box-wrap-4297 .aio-icon-description" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';color:#717070;"><p>English opens many doors in life and can be your route to a successful future.</p>
                                        </div> <!-- description --></div> <!-- aio-ibd-block --></div> <!-- aio-icon-box --></div> <!-- aio-icon-component --><div class="ult-spacer spacer-57412231521a3" data-id="57412231521a3" data-height="10" data-height-mobile="10" data-height-tab="10" data-height-tab-portrait="" data-height-mobile-landscape="" style="clear:both;display:block;"></div><div class="aio-icon-component   lin-classess-icon-1 style_1"><div id="Info-box-wrap-9815" class="aio-icon-box left-icon" style=""><div class="aio-icon-left"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                <div class="aio-icon advanced  animated bounceInLeft delay-03" data-animation="bounceInLeft" data-animation-delay="03" style="color:#ffffff;background:#377bab;border-style:solid;border-color:#ffc000;border-width:6px;width:100px;height:100px;line-height:100px;border-radius:120px;font-size:35px;display:inline-block;">
                                                    <i class="linear-star-half"></i>
                                                </div></div></div></div><div class="aio-ibd-block"><div class="aio-icon-header"><h3 class="aio-icon-title ult-responsive" data-ultimate-target="#Info-box-wrap-9815 .aio-icon-title" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:27px;&quot;}" style="font-family:'Raleway';font-weight:800;color:#333333;">SHAPES AND MEASURES</h3></div> <!-- header --><div class="aio-icon-description ult-responsive" data-ultimate-target="#Info-box-wrap-9815 .aio-icon-description" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';color:#717070;"><p>English opens many doors in life and can be your route to a successful future.</p>
                                        </div> <!-- description --></div> <!-- aio-ibd-block --></div> <!-- aio-icon-box --></div> <!-- aio-icon-component --></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452679374327"><div class="wpb_wrapper"><div class="aio-icon-component   lin-classess-icon-1 style_1"><div id="Info-box-wrap-9296" class="aio-icon-box left-icon" style=""><div class="aio-icon-left"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                <div class="aio-icon advanced  animated bounceInLeft delay-03" data-animation="bounceInLeft" data-animation-delay="03" style="color:#ffffff;background:#377bab;border-style:solid;border-color:#ffc000;border-width:6px;width:100px;height:100px;line-height:100px;border-radius:120px;font-size:35px;display:inline-block;">
                                                    <i class="linear-volume-high"></i>
                                                </div></div></div></div><div class="aio-ibd-block"><div class="aio-icon-header"><h3 class="aio-icon-title ult-responsive" data-ultimate-target="#Info-box-wrap-9296 .aio-icon-title" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:27px;&quot;}" style="font-family:'Raleway';font-weight:800;color:#333333;">UNDERSTANDING</h3></div> <!-- header --><div class="aio-icon-description ult-responsive" data-ultimate-target="#Info-box-wrap-9296 .aio-icon-description" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';color:#717070;"><p>English opens many doors in life and can be your route to a successful future.</p>
                                        </div> <!-- description --></div> <!-- aio-ibd-block --></div> <!-- aio-icon-box --></div> <!-- aio-icon-component --><div class="ult-spacer spacer-5741223152d8e" data-id="5741223152d8e" data-height="10" data-height-mobile="10" data-height-tab="10" data-height-tab-portrait="" data-height-mobile-landscape="" style="clear:both;display:block;"></div><div class="aio-icon-component   lin-classess-icon-1 style_1"><div id="Info-box-wrap-2737" class="aio-icon-box left-icon" style=""><div class="aio-icon-left"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                <div class="aio-icon advanced  animated bounceInLeft delay-03" data-animation="bounceInLeft" data-animation-delay="03" style="color:#ffffff;background:#377bab;border-style:solid;border-color:#ffc000;border-width:6px;width:100px;height:100px;line-height:100px;border-radius:120px;font-size:35px;display:inline-block;">
                                                    <i class="iconsmind-Light-Bulb2"></i>
                                                </div></div></div></div><div class="aio-ibd-block"><div class="aio-icon-header"><h3 class="aio-icon-title ult-responsive" data-ultimate-target="#Info-box-wrap-2737 .aio-icon-title" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:27px;&quot;}" style="font-family:'Raleway';font-weight:800;color:#333333;">SPEAKING</h3></div> <!-- header --><div class="aio-icon-description ult-responsive" data-ultimate-target="#Info-box-wrap-2737 .aio-icon-description" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';color:#717070;"><p>As babies move through their first attempts at communication amazing things.</p>
                                        </div> <!-- description --></div> <!-- aio-ibd-block --></div> <!-- aio-icon-box --></div> <!-- aio-icon-component --></div></div></div></div><div class="vc_row-full-width"></div><!-- Row Backgrounds --><div data-vc-full-width="true" data-vc-full-width-init="true" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid vc_custom_1454939061687 vc_row-no-padding" style="position: relative; left: -58px; box-sizing: border-box; width: 1286px;"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner vc_custom_1452601815321"><div class="wpb_wrapper"><!-- vc_grid start -->
                            <div class="vc_grid-container-wrapper vc_clearfix">
                                <div class="vc_grid-container vc_clearfix wpb_content_element vc_media_grid" data-vc-grid-settings="{&quot;page_id&quot;:9609,&quot;style&quot;:&quot;all&quot;,&quot;action&quot;:&quot;vc_get_vc_grid_data&quot;,&quot;animation_in&quot;:&quot;zoomIn&quot;,&quot;shortcode_id&quot;:&quot;1455372619106-bfd1ae46-3ad9-1&quot;,&quot;tag&quot;:&quot;vc_media_grid&quot;}" data-vc-request="/wp/wp-admin/admin-ajax.php" data-vc-post-id="9609" data-vc-public-nonce="d3f0da6880">
                                    <style type="text/css">
                                        img.wp-smiley,
                                        img.emoji {
                                            display: inline !important;
                                            border: none !important;
                                            box-shadow: none !important;
                                            height: 1em !important;
                                            width: 1em !important;
                                            margin: 0 .07em !important;
                                            vertical-align: -0.1em !important;
                                            background: none !important;
                                            padding: 0 !important;
                                        }
                                    </style>
                                    <div class="vc_grid vc_row vc_pageable-wrapper vc_hook_hover" data-vc-pageable-content="true"><div class="vc_pageable-slide-wrapper vc_clearfix" data-vc-grid-content="true"><div class="vc_grid-item vc_clearfix vc_col-sm-3 vc_visible-item zoomIn animated"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-1-1 vc_gitem-is-link" style="background-image: url(http://skilled.aislinthemes.com/app/uploads/2016/02/04.png) !important;">
                                                            <a href="http://skilled.aislinthemes.com/app/uploads/2016/02/04.png" title="04" rel="prettyPhoto[rel--1881193935]" data-vc-gitem-zone="prettyphotoLink" class="vc_gitem-link prettyphoto vc-zone-link vc-prettyphoto-link"></a>	<img src="http://skilled.aislinthemes.com/app/uploads/2016/02/04.png" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-3 vc_visible-item zoomIn animated"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-1-1 vc_gitem-is-link" style="background-image: url(http://skilled.aislinthemes.com/app/uploads/2016/02/03.png) !important;">
                                                            <a href="http://skilled.aislinthemes.com/app/uploads/2016/02/03.png" title="03" rel="prettyPhoto[rel--1881193935]" data-vc-gitem-zone="prettyphotoLink" class="vc_gitem-link prettyphoto vc-zone-link vc-prettyphoto-link"></a>	<img src="http://skilled.aislinthemes.com/app/uploads/2016/02/03.png" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-3 vc_visible-item zoomIn animated"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-1-1 vc_gitem-is-link" style="background-image: url(http://skilled.aislinthemes.com/app/uploads/2016/02/02.png) !important;">
                                                            <a href="http://skilled.aislinthemes.com/app/uploads/2016/02/02.png" title="02" rel="prettyPhoto[rel--1881193935]" data-vc-gitem-zone="prettyphotoLink" class="vc_gitem-link prettyphoto vc-zone-link vc-prettyphoto-link"></a>	<img src="http://skilled.aislinthemes.com/app/uploads/2016/02/02.png" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-3 vc_visible-item zoomIn animated"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-1-1 vc_gitem-is-link" style="background-image: url(http://skilled.aislinthemes.com/app/uploads/2016/02/01.png) !important;">
                                                            <a href="http://skilled.aislinthemes.com/app/uploads/2016/02/01.png" title="01" rel="prettyPhoto[rel--1881193935]" data-vc-gitem-zone="prettyphotoLink" class="vc_gitem-link prettyphoto vc-zone-link vc-prettyphoto-link"></a>	<img src="http://skilled.aislinthemes.com/app/uploads/2016/02/01.png" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div><div class="vc_clearfix"></div></div></div></div></div>
                            </div><!-- vc_grid end -->
                        </div></div></div></div><div class="vc_row-full-width"></div><!-- Row Backgrounds --><div data-vc-full-width="true" data-vc-full-width-init="true" class="vc_row wpb_row vc_row-fluid vc_custom_1455026924595 vc_row-has-fill" style="position: relative; left: -58px; box-sizing: border-box; width: 1286px; padding-left: 58px; padding-right: 58px;"><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1454939499838"><div class="wpb_wrapper"><div id="ultimate-heading-27445741223156597" class="uvc-heading ult-adjust-bottom-margin ultimate-heading-27445741223156597 uvc-7193 " data-hspacer="no_spacer" data-halign="center" style="text-align:center"><div class="uvc-heading-spacer no_spacer" style="top"></div><div class="uvc-main-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-27445741223156597 h2" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:32px;&quot;}"><h2 style="font-family:'Raleway';font-weight:800;color:#363636;margin-bottom:7px;">10,000+ LESSONS</h2></div><div class="uvc-sub-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-27445741223156597 .uvc-sub-heading " data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:normal;margin-bottom:15px;"><p>Our expert instructors cover Math, Science, English, History, Test Prep and more for college.</p>
                                </div></div><div class=" ubtn-ctn-center "><button type="button" id="ubtn-2246" class="ubtn ult-adjust-bottom-margin ult-responsive ubtn-custom ubtn-no-hover-bg  ulta-hover  ubtn-center   tooltip-57412231566a2" data-hover="" data-border-color="" data-bg="#ffc000" data-hover-bg="" data-border-hover="" data-shadow-hover="" data-shadow-click="none" data-shadow="" data-shd-shadow="" data-ultimate-target="#ubtn-2246" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:13px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="font-family:'Raleway';font-weight:700;width:px;min-height:px;padding:12px 20px;border:none;background: #ffc000;color: #ffffff;"><span class="ubtn-hover" style="background-color:"></span><span class="ubtn-data ubtn-text ">LEARN MORE</span></button></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1454939749285"><div class="wpb_wrapper"><div id="ultimate-heading-55845741223156bc4" class="uvc-heading ult-adjust-bottom-margin ultimate-heading-55845741223156bc4 uvc-753 " data-hspacer="no_spacer" data-halign="center" style="text-align:center"><div class="uvc-heading-spacer no_spacer" style="top"></div><div class="uvc-main-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-55845741223156bc4 h2" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:32px;&quot;}"><h2 style="font-family:'Raleway';font-weight:800;color:#363636;margin-bottom:7px;">SIMPLE AND FUN VIDEOS</h2></div><div class="uvc-sub-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-55845741223156bc4 .uvc-sub-heading " data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:normal;margin-bottom:15px;"><p>Difficult subjects explained with simple, bite-sized lessons. Plus, engaging examples.</p>
                                </div></div><div class=" ubtn-ctn-center "><button type="button" id="ubtn-3395" class="ubtn ult-adjust-bottom-margin ult-responsive ubtn-custom ubtn-no-hover-bg  ulta-hover  ubtn-center   tooltip-5741223156cc1" data-hover="" data-border-color="" data-bg="#ffc000" data-hover-bg="" data-border-hover="" data-shadow-hover="" data-shadow-click="none" data-shadow="" data-shd-shadow="" data-ultimate-target="#ubtn-3395" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:13px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="font-family:'Raleway';font-weight:700;width:px;min-height:px;padding:12px 20px;border:none;background: #ffc000;color: #ffffff;"><span class="ubtn-hover" style="background-color:"></span><span class="ubtn-data ubtn-text ">LEARN MORE</span></button></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1454939755940"><div class="wpb_wrapper"><div id="ultimate-heading-1312574122315725a" class="uvc-heading ult-adjust-bottom-margin ultimate-heading-1312574122315725a uvc-8759 " data-hspacer="no_spacer" data-halign="center" style="text-align:center"><div class="uvc-heading-spacer no_spacer" style="top"></div><div class="uvc-main-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-1312574122315725a h2" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:18px;&quot;,&quot;line-height&quot;:&quot;desktop:32px;&quot;}"><h2 style="font-family:'Raleway';font-weight:800;color:#363636;margin-bottom:7px;">UNLIMITED ACCESS</h2></div><div class="uvc-sub-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-1312574122315725a .uvc-sub-heading " data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:normal;margin-bottom:15px;"><p>Access to our entire library of self-paced lessons, anytime, anywhere, even on the go.</p>
                                </div></div><div class=" ubtn-ctn-center "><button type="button" id="ubtn-9836" class="ubtn ult-adjust-bottom-margin ult-responsive ubtn-custom ubtn-no-hover-bg  ulta-hover  ubtn-center   tooltip-57412231573bc" data-hover="" data-border-color="" data-bg="#ffc000" data-hover-bg="" data-border-hover="" data-shadow-hover="" data-shadow-click="none" data-shadow="" data-shd-shadow="" data-ultimate-target="#ubtn-9836" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:13px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="font-family:'Raleway';font-weight:700;width:px;min-height:px;padding:12px 20px;border:none;background: #ffc000;color: #ffffff;"><span class="ubtn-hover" style="background-color:"></span><span class="ubtn-data ubtn-text ">LEARN MORE</span></button></div></div></div></div></div><div class="vc_row-full-width"></div><div class="vc_row wpb_row vc_row-fluid vc_custom_1455026954346"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner vc_custom_1455187966970"><div class="wpb_wrapper"><div id="ultimate-heading-775741223157dff" class="uvc-heading ult-adjust-bottom-margin ultimate-heading-775741223157dff uvc-763 " data-hspacer="no_spacer" data-halign="center" style="text-align:center"><div class="uvc-heading-spacer no_spacer" style="top"></div><div class="uvc-main-heading ult-responsive" data-ultimate-target=".uvc-heading.ultimate-heading-775741223157dff h2" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:26px;&quot;,&quot;line-height&quot;:&quot;desktop:45px;&quot;}"><h2 style="font-family:'Raleway';font-weight:900;color:#333333;margin-bottom:20px;">SERVICE OVERVIEW</h2></div></div><div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_100 vc_sep_pos_align_center vc_separator_no_text vc_sep_color_grey  lin-vc-separator"><span class="vc_sep_holder vc_sep_holder_l"><span class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span class="vc_sep_line"></span></span>
                            </div></div></div></div></div><div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_row wpb_row vc_inner vc_row-fluid vc_custom_1449830525402 vc_row-has-fill"><div class="wpb_column vc_column_container vc_col-sm-4 vc_col-has-fill"><div class="vc_column-inner vc_custom_1448021407279"><div class="wpb_wrapper"><div class="flip-box-wrap" style=""><div class="flip-box ifb-jq-height  horizontal_flip_left flip-ifb-jq-height" style=""><div class="ifb-flip-box" id="flip-box-wrap-1332"><div class="ifb-face ifb-front " style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section ">
                                                                <div class="flip-box-icon"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                                            <div class="aio-icon none " style="color:rgba(255,255,255,0.9);font-size:55px;display:inline-block;">
                                                                                <i class="linear-laptop-phone"></i>
                                                                            </div></div></div></div><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-1332 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">DEVELOPER</h3><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-1332 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>$50/month</p></div></div></div><!-- END .front -->
                                                        <div class="ifb-face ifb-back" style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section "><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-1332 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">MORE INFO</h3><div class="ifb-desc-back"><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-1332 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>Enroll in online classes taught by creators from</p></div></div><div class="flip_link"><a href="http://skilled.aislinthemes.com/services-02/" style="background:#ffffff; color:#ffc11b;">MORE INFO</a></div></div></div><!-- END .back --></div> <!-- ifb-flip-box --></div> <!-- flip-box --></div><!-- End icon block --></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452239139754"><div class="wpb_wrapper"><div class="flip-box-wrap" style=""><div class="flip-box ifb-jq-height  horizontal_flip_left flip-ifb-jq-height" style=""><div class="ifb-flip-box" id="flip-box-wrap-4753"><div class="ifb-face ifb-front " style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section ">
                                                                <div class="flip-box-icon"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                                            <div class="aio-icon none " style="color:rgba(255,255,255,0.9);font-size:55px;display:inline-block;">
                                                                                <i class="linear-layers"></i>
                                                                            </div></div></div></div><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-4753 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">WEB DESIGN</h3><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-4753 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>$50/month</p></div></div></div><!-- END .front -->
                                                        <div class="ifb-face ifb-back" style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section "><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-4753 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">MORE INFO</h3><div class="ifb-desc-back"><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-4753 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>Enroll in online classes taught by creators from</p></div></div><div class="flip_link"><a href="http://skilled.aislinthemes.com/services-02/" style="background:#ffffff; color:#ffc11b;">MORE INFO</a></div></div></div><!-- END .back --></div> <!-- ifb-flip-box --></div> <!-- flip-box --></div><!-- End icon block --></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452239211225"><div class="wpb_wrapper"><div class="flip-box-wrap" style=""><div class="flip-box ifb-jq-height  horizontal_flip_left flip-ifb-jq-height" style=""><div class="ifb-flip-box" id="flip-box-wrap-2567"><div class="ifb-face ifb-front " style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section ">
                                                                <div class="flip-box-icon"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                                            <div class="aio-icon none " style="color:rgba(255,255,255,0.9);font-size:55px;display:inline-block;">
                                                                                <i class="linear-briefcase"></i>
                                                                            </div></div></div></div><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-2567 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">BUSINESS</h3><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-2567 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>$50/month</p></div></div></div><!-- END .front -->
                                                        <div class="ifb-face ifb-back" style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section "><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-2567 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">MORE INFO</h3><div class="ifb-desc-back"><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-2567 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>Enroll in online classes taught by creators from</p></div></div><div class="flip_link"><a href="http://skilled.aislinthemes.com/services-02/" style="background:#ffffff; color:#ffc11b;">MORE INFO</a></div></div></div><!-- END .back --></div> <!-- ifb-flip-box --></div> <!-- flip-box --></div><!-- End icon block --></div></div></div></div><div class="vc_row wpb_row vc_inner vc_row-fluid vc_custom_1448133329933 vc_row-has-fill"><div class="wpb_column vc_column_container vc_col-sm-4 vc_col-has-fill"><div class="vc_column-inner vc_custom_1448021407279"><div class="wpb_wrapper"><div class="flip-box-wrap" style=""><div class="flip-box ifb-jq-height  horizontal_flip_left flip-ifb-jq-height" style=""><div class="ifb-flip-box" id="flip-box-wrap-7391"><div class="ifb-face ifb-front " style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section ">
                                                                <div class="flip-box-icon"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                                            <div class="aio-icon none " style="color:rgba(255,255,255,0.9);font-size:55px;display:inline-block;">
                                                                                <i class="linear-flag"></i>
                                                                            </div></div></div></div><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-7391 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">LANGUAGES</h3><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-7391 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>$50/month</p></div></div></div><!-- END .front -->
                                                        <div class="ifb-face ifb-back" style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section "><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-7391 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">MORE INFO</h3><div class="ifb-desc-back"><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-7391 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>Enroll in online classes taught by creators from</p></div></div><div class="flip_link"><a href="http://skilled.aislinthemes.com/services-02/" style="background:#ffffff; color:#ffc11b;">MORE INFO</a></div></div></div><!-- END .back --></div> <!-- ifb-flip-box --></div> <!-- flip-box --></div><!-- End icon block --></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452239258977"><div class="wpb_wrapper"><div class="flip-box-wrap" style=""><div class="flip-box ifb-jq-height  horizontal_flip_left flip-ifb-jq-height" style=""><div class="ifb-flip-box" id="flip-box-wrap-9042"><div class="ifb-face ifb-front " style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section ">
                                                                <div class="flip-box-icon"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                                            <div class="aio-icon none " style="color:rgba(255,255,255,0.9);font-size:55px;display:inline-block;">
                                                                                <i class="linear-store"></i>
                                                                            </div></div></div></div><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-9042 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">E-COMMERCE</h3><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-9042 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>$50/month</p></div></div></div><!-- END .front -->
                                                        <div class="ifb-face ifb-back" style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section "><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-9042 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">MORE INFO</h3><div class="ifb-desc-back"><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-9042 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>Enroll in online classes taught by creators from</p></div></div><div class="flip_link"><a href="http://skilled.aislinthemes.com/services-02/" style="background:#ffffff; color:#ffc11b;">MORE INFO</a></div></div></div><!-- END .back --></div> <!-- ifb-flip-box --></div> <!-- flip-box --></div><!-- End icon block --></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1452601914831"><div class="wpb_wrapper"><div class="flip-box-wrap" style=""><div class="flip-box ifb-jq-height  horizontal_flip_left flip-ifb-jq-height" style=""><div class="ifb-flip-box" id="flip-box-wrap-2906"><div class="ifb-face ifb-front " style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section ">
                                                                <div class="flip-box-icon"><div class="ult-just-icon-wrapper  "><div class="align-icon" style="text-align:center;">
                                                                            <div class="aio-icon none " style="color:rgba(255,255,255,0.9);font-size:55px;display:inline-block;">
                                                                                <i class="linear-star"></i>
                                                                            </div></div></div></div><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-2906 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">DEVELOPER</h3><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-2906 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>$50/month</p></div></div></div><!-- END .front -->
                                                        <div class="ifb-face ifb-back" style="color: rgb(255, 255, 255); border: 0px solid rgb(255, 255, 255); height: 185px; background: rgb(255, 193, 27);">
                                                            <div class="ifb-flip-box-section "><h3 class="ult-responsive" data-ultimate-target="#flip-box-wrap-2906 h3.ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;&quot;}" style="color:#ffffff; font-family:'Raleway';font-weight:800;">MORE INFO</h3><div class="ifb-desc-back"><div class="ifb-flip-box-section-content ult-responsive" data-ultimate-target="#flip-box-wrap-2906 .ult-responsive" data-responsive-json-new="{&quot;font-size&quot;:&quot;desktop:14px;&quot;,&quot;line-height&quot;:&quot;desktop:22px;&quot;}" style="font-family:'Raleway';font-weight:300;color:#333333;color:#ffffff;"><p>Enroll in online classes taught by creators from</p></div></div><div class="flip_link"><a href="http://skilled.aislinthemes.com/services-02/" style="background:#ffffff; color:#ffc11b;">MORE INFO</a></div></div></div><!-- END .back --></div> <!-- ifb-flip-box --></div> <!-- flip-box --></div><!-- End icon block --></div></div></div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner vc_custom_1455187981301"><div class="wpb_wrapper">
                            <div class="wpb_accordion wpb_content_element  not-column-inherit" data-collapsible="" data-vc-disable-keydown="false" data-active-tab="1">
                                <div class="wpb_wrapper wpb_accordion_wrapper ui-accordion ui-widget ui-helper-reset" role="tablist">


                                    <div class="wpb_accordion_section group">
                                        <h3 class="wpb_accordion_header ui-accordion-header ui-state-default ui-accordion-header-active ui-state-active ui-corner-top ui-accordion-icons" role="tab" id="ui-id-1" aria-controls="ui-id-2" aria-selected="true" aria-expanded="true" tabindex="0"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-s iconsmind-minus"></span><a href="#learn-from-ajax-pro">Learn from AJAX Pro</a></h3>
                                        <div class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active" id="ui-id-2" aria-labelledby="ui-id-1" role="tabpanel" style="display: block;" aria-hidden="false">

                                            <div class="wpb_text_column wpb_content_element  vc_custom_1454593299044">
                                                <div class="wpb_wrapper">
                                                    <p><span style="color: #666666;">From emptying a litter box, to walking and feeding, we’re here to make sure your pet is cared for as well.&nbsp;We also offer a variety of accommodation options, fun social activities.</span></p>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="wpb_accordion_section group">
                                        <h3 class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-id-3" aria-controls="ui-id-4" aria-selected="false" aria-expanded="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e iconsmind-plus"></span><a href="#learn-from-3d-pro">Learn from 3D Pro</a></h3>
                                        <div class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-id-4" aria-labelledby="ui-id-3" role="tabpanel" aria-hidden="true" style="display: none;">

                                            <div class="wpb_text_column wpb_content_element  vc_custom_1449311566289">
                                                <div class="wpb_wrapper">
                                                    <p><span style="color: #666666;">From emptying a litter box, to walking and feeding, we’re here to make sure your pet is cared for as well.</span></p>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="wpb_accordion_section group">
                                        <h3 class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-id-5" aria-controls="ui-id-6" aria-selected="false" aria-expanded="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e iconsmind-plus"></span><a href="#learn-from-photoshop-pro">Learn from Photoshop Pro</a></h3>
                                        <div class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-id-6" aria-labelledby="ui-id-5" role="tabpanel" aria-hidden="true" style="display: none;">

                                            <div class="wpb_text_column wpb_content_element  vc_custom_1449311580048">
                                                <div class="wpb_wrapper">
                                                    <p><span style="color: #666666;">From emptying a litter box, to walking and feeding, we’re here to make sure your pet is cared for as well.</span></p>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="wpb_accordion_section group">
                                        <h3 class="wpb_accordion_header ui-accordion-header ui-state-default ui-corner-all ui-accordion-icons" role="tab" id="ui-id-7" aria-controls="ui-id-8" aria-selected="false" aria-expanded="false" tabindex="-1"><span class="ui-accordion-header-icon ui-icon ui-icon-triangle-1-e iconsmind-plus"></span><a href="#learn-from-photoshop-pro">Learn from Photoshop Pro</a></h3>
                                        <div class="wpb_accordion_content ui-accordion-content vc_clearfix ui-helper-reset ui-widget-content ui-corner-bottom" id="ui-id-8" aria-labelledby="ui-id-7" role="tabpanel" aria-hidden="true" style="display: none;">

                                            <div class="wpb_text_column wpb_content_element  vc_custom_1449311592170">
                                                <div class="wpb_wrapper">
                                                    <p><span style="color: #666666;">From emptying a litter box, to walking and feeding, we’re here to make sure your pet is cared for as well.</span></p>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div></div></div></div>


        </div>
    </div>
</div>

    <?php include 'footer.php'; ?>
